ALTER TABLE "dish_templates"
  ADD COLUMN IF NOT EXISTS "ingredients" TEXT,
  ADD COLUMN IF NOT EXISTS "allergens" TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "serving_size" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "serving_unit" TEXT,
  ADD COLUMN IF NOT EXISTS "fat_saturated" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "fat_trans" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "cholesterol" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sodium" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "fiber" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sugar_total" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "sugar_added" DOUBLE PRECISION;

ALTER TABLE "dish_templates" DROP COLUMN IF EXISTS "allergen_disclaimer";
