ALTER TABLE "orders" ADD COLUMN "tax_id_type" TEXT NOT NULL DEFAULT '07';
ALTER TABLE "orders" ADD COLUMN "tax_id" TEXT NOT NULL DEFAULT '9999999999999';
ALTER TABLE "orders" ADD COLUMN "invoice_number" SERIAL;
