ALTER TABLE "orders" DROP COLUMN IF EXISTS "address_id";

DROP TABLE IF EXISTS "box_items" CASCADE;
DROP TABLE IF EXISTS "weekly_boxes" CASCADE;
DROP TABLE IF EXISTS "addresses" CASCADE;
DROP TABLE IF EXISTS "dishes" CASCADE;
